### ISSUE TITLE
Code 19 in device manager

### ISSUE THREAD

**Issue by nex86** [zjquid/t440p_fix#1]
I tried this method on my T440P with Synaptics trackpad.
It works fine after first reboot but when I reboot another time I my trackpad AND keyboard both stop responding and I get code 19 in device manager for synaptics trackpad.
I tried the gpedit method but it didn't work.

**Comment by zjquid** [comment]
did you try other regedit methods before this? there might be some conflict if you tried one method, it didn't work, then tried another etc.
try uninstalling the synaptics driver, rebooting, and see if the trackpad works like "normal" (normal for T440p stock drivers).
keyboard not working is strange.... maybe the ribbon cable is loose/crooked? although I think code 19 is specific to the registry, which is voodoo to me, I don't know how it all connects.
after that, repeat the driver install process and see if it returns
edit: if you've been using this win10 installation for a while and did a registry edit in the past, it may be conflicting with the trackpad regedit. I guess the next step would be to try on a fresh windows install and see if the problem arises then
